name: Rail
version: ${project.version}
description: Automation stuff.
website: http://phanta.xyz
main: io.github.phantamanta44.mcrail.Rail
commands:
  ritems:
    usage: "/ritems [page|regex]"
    description: Lists available custom item IDs for Rail.
  ritem:
    usage: "/ritem <id> [amount]"
    description: Spawns an amount of custom items by ID.
permissions:
  rail.items:
    description: "Allows the usage of /ritems."
  rail.item:
    description: "Allows the usage of /ritem."